### ISSUE TITLE
handle -c channel mode

### ISSUE THREAD

**Issue by moopie** [anlutro/botologist#25]
bot can't into speak when color is not allowed on channel

**Comment by anlutro** [comment]
The bot can either find the channel modes out on its own or have an `enable_colors: true/false` set for each individual channel. The latter is obviously less effort.

Bold/color codes can either be removed using `str.replace` or `re.replace`, or by abstracting away how special IRC symbols are applied - for example, instead of sending `\x02bold\x0F` directly, send `%(bold)bold%(reset)` and let the IRC client/bot instance decide how to format it.

**Comment by anlutro** [comment]
Forgot to close - fixed by https://github.com/anlutro/botologist/commit/f223041e49dff1c4d0f445ffca1e79fe0f7b5309
